### ISSUE TITLE
大佬运行报错 这是啥问题呢

### ISSUE THREAD

**Issue by miaomiaojianglove** [dothetrick/binlogportal#6]
2021-11-10 14:18:04.262  WARN 25352 --- [iyuncs.com:3306] c.g.shyiko.mysql.binlog.BinaryLogClient  : com.insistingon.binlogportal.event.MultiEventHandlerListener@4a7c22b1 choked on Event{header=EventHeaderV4{timestamp=1636524980000, eventType=UPDATE_ROWS, serverId=19404926, headerLength=19, dataLength=4385, nextPosition=280448513, flags=0}, data=UpdateRowsEventData{tableId=327, includedColumnsBeforeUpdate={0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27}, includedColumns={0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27}, rows=[
    {before=[2411, [B@491e63ae, -1.00, 0.00, 299.00, 4.00, 0.00, 13, 4, 0, 0, 100, 5, 0, 2, 4, 6, 0, [B@198954f2, [B@644f887d, [B@262dacf6, [B@1c94b88e, [B@4fe9412a, [B@577d34ca, [B@1c7c68cf, 1613460000, 1629539443000, 1629539443000], after=[2411, [B@2515f306, -1.00, 0.00, 299.00, 4.00, 0.00, 13, 4, 0, 0, 100, 5, 5, 2, 4, 6, 0, [B@2070069f, [B@1e15ad3f, [B@61d08422, [B@6bd7d6dd, [B@4bb361c6, [B@787c41da, [B@1de83b63, 1613460000, 1629539443000, 1629539443000]}
]}}

java.lang.NullPointerException: null
	at com.insistingon.binlogportal.event.MultiEventHandlerListener.lambda$null$0(MultiEventHandlerListener.java:113) ~[binlogportal-1.0.11.jar:na]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[na:1.8.0_291]
	at com.insistingon.binlogportal.event.MultiEventHandlerListener.lambda$onEvent$1(MultiEventHandlerListener.java:111) ~[binlogportal-1.0.11.jar:na]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[na:1.8.0_291]
	at com.insistingon.binlogportal.event.MultiEventHandlerListener.onEvent(MultiEventHandlerListener.java:110) ~[binlogportal-1.0.11.jar:na]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.notifyEventListeners(BinaryLogClient.java:1158) [mysql-binlog-connector-java-0.21.0.jar:0.21.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:1005) [mysql-binlog-connector-java-0.21.0.jar:0.21.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connectWithTimeout(BinaryLogClient.java:517) [mysql-binlog-connector-java-0.21.0.jar:0.21.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.access$1100(BinaryLogClient.java:90) [mysql-binlog-connector-java-0.21.0.jar:0.21.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:881) [mysql-binlog-connector-java-0.21.0.jar:0.21.0]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_291]

**Comment by peng909300035** [comment]
我也遇到了同样的问题

**Comment by dothetrick** [comment]
mysql版本和使用的jar包版本发下

**Comment by peng909300035** [comment]
mysql版本 5.7.21  使用的binlogportal  1.0.12

**Comment by miaomiaojianglove** [comment]
mysql是5.7 驱动
 <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.26</version>
        </dependency>
项目是直接当前您这个项目直接克隆的

**Comment by miaomiaojianglove** [comment]
binlogportal   1.0.11 版本我下载您的源码运行也是同样错误

**Comment by dothetrick** [comment]
确认下事件监听处理类，是否已经注册到了spring的ioc中。
![image](https://user-images.githubusercontent.com/10044737/141400696-92bf359f-55b4-467a-beec-6e228c7f7042.png)

**Comment by dothetrick** [comment]
源码里面的日志路径是这个，看下当前运行的机器是否没有文件权限。
```java
logging:
  file:
    path: /var/log/binlogportal
```

**Comment by miaomiaojianglove** [comment]
这个logEventHandler指的是啥呢 有例子嘛 这个我当时以为是固定死的一个您封装的处理类
@Slf4j
@Component
public class BinlogSync implements CommandLineRunner {
    @Autowired
    BinlogPortalStarter binlogPortalStarter;

    public void run(String... args){
        try {
            binlogPortalStarter.start();
        } catch (BinlogPortalException e) {
            log.error(e.getMessage(), e);
        }
    }
}

**Comment by dothetrick** [comment]
可以参考下源码里面，com.insistingon.binlogportal.binlogportalspringbootstartertest.eventhandler.LogEventHandler这个类。这是个demo.

eventhandler是接收到binlog信息后，实际要做的处理，是需要根据自己的需求实现的。

**Comment by dothetrick** [comment]
源码中可以直接运行springboot项目，com.insistingon.binlogportal.binlogportalspringbootstartertest.BinlogportalSpringBootStarterTestApplication

这个是已经配置好的springboot项目

**Comment by peng909300035** [comment]
就是运行这个也会报错  
![image](https://user-images.githubusercontent.com/32948676/141404583-336abb9d-48f9-40a7-933f-8b0bc9a192ae.png)

**Comment by miaomiaojianglove** [comment]
同楼上也是一样会报错

**Comment by miaomiaojianglove** [comment]
断点调试是数组内一共有两个元素 第一个是null的 第二个是url

**Comment by peng909300035** [comment]
![image](https://user-images.githubusercontent.com/32948676/141406382-5c2ca963-9eb7-49c9-b786-758d5bf2987d.png)
这个路径会有影响么  因为是在windows机器上试的  不过尝试了把路径改成 D:\\binlogportal  还是报错

**Comment by dothetrick** [comment]
看下你们用的mysql的binlog记录格式，是row类型么？

**Comment by peng909300035** [comment]
是的  我用main方法的那种写法 可以正常运行  想和springboot结合用  一修改mysql的数据 就会报上面的错误

**Comment by dothetrick** [comment]
main方法的方式，需要再启动前加一行，

syncConfig.setEventHandlerList(Collections.singletonList(eventEntity -> System.out.println(eventEntity.getJsonFormatData())));

加上运行下，看能打印出变更内容么

**Comment by miaomiaojianglove** [comment]
我的binlog 是row类型

**Comment by peng909300035** [comment]
可以  增删改查 都可以

**Comment by peng909300035** [comment]
增删改 都可以

**Comment by peng909300035** [comment]
只是和springboot结合使用 就出现了问题

**Comment by miaomiaojianglove** [comment]
> 只是和springboot结合使用 就出现了问题

老哥你的main方法运行方式能贴下代码嘛 我看的有点云里雾里的

**Comment by dothetrick** [comment]
> > 只是和springboot结合使用 就出现了问题
> 
> 老哥你的main方法运行方式能贴下代码嘛 我看的有点云里雾里的

main方法我修改过了，更新下源码运行看看

**Comment by miaomiaojianglove** [comment]
报错信息
![image](https://user-images.githubusercontent.com/28811199/141408231-3e51f717-f0a0-436d-ae5d-afe4efc84087.png)

**Comment by dothetrick** [comment]
> 报错信息 ![image](https://user-images.githubusercontent.com/28811199/141408231-3e51f717-f0a0-436d-ae5d-afe4efc84087.png)

这里应该加上这一行，
![image](https://user-images.githubusercontent.com/10044737/141408366-3c6a7777-4882-4060-87e2-bdc2337b7a52.png)

**Comment by dothetrick** [comment]
> 只是和springboot结合使用 就出现了问题

我刚试了几次，没重现这个问题。麻烦把表结构，springboot.xml的配置发下，

还有在mysql中执行下，`SHOW VARIABLES like "%binlog%";` 这个命令，返回的信息也贴下看看

**Comment by miaomiaojianglove** [comment]
我重新拉下源码试试看 我上面的截图是SpringBoot的方式运行错误 不是main的

**Comment by miaomiaojianglove** [comment]
您的SpringBoot方式能够运行吗 大佬

**Comment by dothetrick** [comment]
> 您的SpringBoot方式能够运行吗 大佬

我的可以的，刚试过。你上面那个报错就是eventhandler没有在spring里创建成功，所以列表里没有处理类。

demo里面创建成功后运行会打出变更日志。
![image](https://user-images.githubusercontent.com/10044737/141408807-360d9a0a-5614-4467-91cb-6ba6a46b42d2.png)

**Comment by miaomiaojianglove** [comment]
请问大佬您是改什么东西了嘛 我重新拉了一份源码 直接运行成功了

**Comment by miaomiaojianglove** [comment]
我好像明白了 的项目内没有加那个监听器的bean LogEventHandler 我加上运行以后报错
2021-11-12 12:29:38.725 ERROR 12324 --- [      Thread-20] c.i.binlogportal.BinlogPortalStarter     : binaryLogClient connect error!com.github.shyiko.mysql.binlog.BinaryLogClient@2057f0dc
这个啥啥情况呀大佬

**Comment by miaomiaojianglove** [comment]
回刚刚那个错误 是偶尔启动时候会报错 我删除redis内的binlog记录重新启动就没问题了 
启动以后报错
2021-11-12 12:32:40.876  WARN 12328 --- [      Thread-19] c.g.shyiko.mysql.binlog.BinaryLogClient  : com.insistingon.binlogportal.event.MultiEventHandlerListener@7ba0b7b6 choked on Event{header=EventHeaderV4{timestamp=1636691560000, eventType=WRITE_ROWS, serverId=19404926, headerLength=19, dataLength=48, nextPosition=281890913, flags=0}, data=WriteRowsEventData{tableId=73, includedColumns={0, 1, 2, 3, 4}, rows=[
    [1597, 130570, 8424, 0, 1636720360000]
]}}

java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
	at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[na:1.8.0_291]
	at java.util.ArrayList.get(ArrayList.java:435) ~[na:1.8.0_291]
	at com.insistingon.binlogportal.event.EventEntity.getJsonFormatData(EventEntity.java:111) ~[binlogportal-1.0.11.jar:na]
	at com.tianju.smdk.common.LogEventHandler.process(LogEventHandler.java:13) ~[classes/:na]
	at com.insistingon.binlogportal.event.MultiEventHandlerListener.lambda$null$0(MultiEventHandlerListener.java:113) ~[binlogportal-1.0.11.jar:na]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[na:1.8.0_291]
	at com.insistingon.binlogportal.event.MultiEventHandlerListener.lambda$onEvent$1(MultiEventHandlerListener.java:111) ~[binlogportal-1.0.11.jar:na]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[na:1.8.0_291]
	at com.insistingon.binlogportal.event.MultiEventHandlerListener.onEvent(MultiEventHandlerListener.java:110) ~[binlogportal-1.0.11.jar:na]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.notifyEventListeners(BinaryLogClient.java:1055) [mysql-binlog-connector-java-0.16.1.jar:0.16.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:913) [mysql-binlog-connector-java-0.16.1.jar:0.16.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:559) [mysql-binlog-connector-java-0.16.1.jar:0.16.1]
	at com.insistingon.binlogportal.BinlogPortalStarter.lambda$null$1(BinlogPortalStarter.java:65) [binlogportal-1.0.11.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_291]

2021-11-12 12:32:41.079  WARN 12328 --- [      Thread-19] c.g.shyiko.mysql.binlog.BinaryLogClient  : com.insistingon.binlogportal.event.MultiEventHandlerListener@7ba0b7b6 choked on Event{header=EventHeaderV4{timestamp=1636691560000, eventType=UPDATE_ROWS, serverId=19404926, headerLength=19, dataLength=1089, nextPosition=281892312, flags=0}, data=UpdateRowsEventData{tableId=66, includedColumnsBeforeUpdate={0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18}, includedColumns={0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18}, rows=[
    {before=[8424, 0, 303, [B@3ac34fd2, [B@e4fa93c, null, 0, -95, 1206, 0, 0, 0, null, 0.00000, 0.00000, 0, 0, 1636710264000, 1629665705000], after=[8424, 0, 303, [B@71e932c7, [B@583d7f7c, null, 1, -95, 1206, 0, 0, 0, null, 0.00000, 0.00000, 0, 0, 1636710264000, 1629665705000]}
]}}

java.lang.IndexOutOfBoundsException: Index: 19, Size: 19
	at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[na:1.8.0_291]
	at java.util.ArrayList.get(ArrayList.java:435) ~[na:1.8.0_291]
	at com.insistingon.binlogportal.event.EventEntity.getJsonFormatData(EventEntity.java:107) ~[binlogportal-1.0.11.jar:na]
	at com.tianju.smdk.common.LogEventHandler.process(LogEventHandler.java:13) ~[classes/:na]
	at com.insistingon.binlogportal.event.MultiEventHandlerListener.lambda$null$0(MultiEventHandlerListener.java:113) ~[binlogportal-1.0.11.jar:na]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[na:1.8.0_291]
	at com.insistingon.binlogportal.event.MultiEventHandlerListener.lambda$onEvent$1(MultiEventHandlerListener.java:111) ~[binlogportal-1.0.11.jar:na]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[na:1.8.0_291]
	at com.insistingon.binlogportal.event.MultiEventHandlerListener.onEvent(MultiEventHandlerListener.java:110) ~[binlogportal-1.0.11.jar:na]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.notifyEventListeners(BinaryLogClient.java:1055) [mysql-binlog-connector-java-0.16.1.jar:0.16.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:913) [mysql-binlog-connector-java-0.16.1.jar:0.16.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:559) [mysql-binlog-connector-java-0.16.1.jar:0.16.1]
	at com.insistingon.binlogportal.BinlogPortalStarter.lambda$null$1(BinlogPortalStarter.java:65) [binlogportal-1.0.11.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_291]

**Comment by miaomiaojianglove** [comment]
报错的代码是         before = this.getChangeBefore().get(i) != null ? this.getChangeBefore().get(i).toString() : ""; 这一行

**Comment by miaomiaojianglove** [comment]
以上错误是我引用jar包在自己的SpringBoot项目内报的错误 我使用您的源码运行没有问题

**Comment by miaomiaojianglove** [comment]
我找到原因了 是因为我版本的问题 我将jar升级到最新版本问题得到了解决 现在就还剩下一个问题  启动时候偶尔会出现
2021-11-12 12:29:38.725 ERROR 12324 --- [ Thread-20] c.i.binlogportal.BinlogPortalStarter : binaryLogClient connect error!com.github.shyiko.mysql.binlog.BinaryLogClient@2057f0dc 
清除redis内的binlog日志再次启动可以得到解决 但是要多次尝试才行

**Comment by miaomiaojianglove** [comment]
报错信息代码
 binaryLogClientList.forEach((binaryLogClient) -> {
            (new Thread(() -> {
                try {
                    binaryLogClient.setHeartbeatInterval(10000L);
                    binaryLogClient.connect();
                } catch (IOException var3) {
                    this.log.error("binaryLogClient connect error!" + binaryLogClient.toString());
                }

            })).start();
        });
求大佬解答

**Comment by miaomiaojianglove** [comment]
连接超时貌似 好像是超时时间设置的太短了如果能设置长点就好了

**Comment by peng909300035** [comment]
你的是怎么跑起来的？  我又重新拉了还是报同样的错误

**Comment by peng909300035** [comment]
![image](https://user-images.githubusercontent.com/32948676/141422872-dde4d99c-72d9-49a0-ba2d-2acc01578fcb.png)
![image](https://user-images.githubusercontent.com/32948676/141423007-09ac86fb-ed1f-46cc-8d53-602e3dee9228.png)
![image](https://user-images.githubusercontent.com/32948676/141423038-a90a823e-cde8-4b0c-9e18-cba1a2c762c5.png)

**Comment by miaomiaojianglove** [comment]
> 你的是怎么跑起来的？ 我又重新拉了还是报同样的错误

老哥你把这个类加进去然后直接启动试试看 我反正是没问题 现在就剩一个连接超时问题了

@Component
@Slf4j
public class LogEventHandler implements IEventHandler {
    public void process(EventEntity eventEntity) throws BinlogPortalException {
        log.info(eventEntity.getJsonFormatData());
    }
}
直接粘贴到你的SpringBoot扫描包下的任意目录 然后重启即可

**Comment by miaomiaojianglove** [comment]
大佬的源码我试了下没问题了 你重新克隆一份试试看

**Comment by miaomiaojianglove** [comment]
> > 您的SpringBoot方式能够运行吗 大佬
> 
> 我的可以的，刚试过。你上面那个报错就是eventhandler没有在spring里创建成功，所以列表里没有处理类。
> 
> demo里面创建成功后运行会打出变更日志。 ![image](https://user-images.githubusercontent.com/10044737/141408807-360d9a0a-5614-4467-91cb-6ba6a46b42d2.png)

恳请大佬看下我的问题 谢谢您

**Comment by peng909300035** [comment]
> 大佬的源码我试了下没问题了 你重新克隆一份试试看

我重新克隆了下 还是同样的问题  你让粘贴的 项目里面已经有了 
![image](https://user-images.githubusercontent.com/32948676/141424326-ef056770-6aef-4e5a-ae78-25b2b83be537.png)

**Comment by miaomiaojianglove** [comment]
> > 大佬的源码我试了下没问题了 你重新克隆一份试试看
> 
> 我重新克隆了下 还是同样的问题 你让粘贴的 项目里面已经有了 ![image](https://user-images.githubusercontent.com/32948676/141424326-ef056770-6aef-4e5a-ae78-25b2b83be537.png)

那我就不太清楚了 但是按理说不应该 你的那个错误就是监听器没有找到导致的 您试试maven clean 或者你看看是不是项目的缓存 当然有没有可能说是项目没有扫描到你的这个监听器

**Comment by peng909300035** [comment]
![image](https://user-images.githubusercontent.com/32948676/141427394-9acd443c-d3fe-4e26-8207-195f4c5b8a7a.png)

**Comment by peng909300035** [comment]
![image](https://user-images.githubusercontent.com/32948676/141429386-475f7724-7bf2-461e-b5b4-5ff7d86e7aef.png)
我更新了一条数据 这里应该进update的 但是EventType 竟然不是update  所以 增删改 都没匹配到  所以返回null了

**Comment by peng909300035** [comment]
![image](https://user-images.githubusercontent.com/32948676/141429636-5d15e962-b813-445d-95a2-70d41b4516a7.png)
这几个都没进

**Comment by miaomiaojianglove** [comment]
> ![image](https://user-images.githubusercontent.com/32948676/141429636-5d15e962-b813-445d-95a2-70d41b4516a7.png) 这几个都没进

我觉得可能是你binlog日志格式设置的有问题

**Comment by dothetrick** [comment]
> 连接超时貌似 好像是超时时间设置的太短了如果能设置长点就好了

启动前加上这行，可以设置连接超时时间，
```java
void start() {
        try {
            //设置连接超时时间，key是application.xml中配置的
            binlogPortalStarter.getClientByDbKey("d1").setConnectTimeout(1000L);
            binlogPortalStarter.start();
        } catch (BinlogPortalException e) {
            log.error(e.getMessage(), e);
        }
    }
```

**Comment by dothetrick** [comment]
@peng909300035 mysql里用这个命令，`SHOW VARIABLES like "%binlog%";`，返回的信息贴下。

类似下面这样的：
![image](https://user-images.githubusercontent.com/10044737/141601915-0bdaf5f4-869e-41b0-94c7-1f8bdeb1a635.png)

**Comment by peng909300035** [comment]
![image](https://user-images.githubusercontent.com/32948676/142195522-c9b544e3-d761-4cbd-8245-31ba529c3157.png)

**Comment by Hkion** [comment]
com.github.shyiko.mysql.binlog.network.AuthenticationException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at com.github.shyiko.mysql.binlog.BinaryLogClient.authenticate(BinaryLogClient.java:755) ~[mysql-binlog-connector-java-0.21.0.jar:0.21.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.openChannelToBinaryLogStream(BinaryLogClient.java:555) ~[mysql-binlog-connector-java-0.21.0.jar:0.21.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connectWithTimeout(BinaryLogClient.java:504) ~[mysql-binlog-connector-java-0.21.0.jar:0.21.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:490) ~[mysql-binlog-connector-java-0.21.0.jar:0.21.0]
	at com.insistingon.binlogportal.distributed.RedisDistributedHandler$1.lambda$run$0(RedisDistributedHandler.java:61) ~[classes/:na]
	at java.util.HashMap.forEach(HashMap.java:1291) ~[na:1.8.0_311]
	at com.insistingon.binlogportal.distributed.RedisDistributedHandler$1.run(RedisDistributedHandler.java:56) ~[classes/:na]
	at java.util.TimerThread.mainLoop(Timer.java:555) ~[na:1.8.0_311]
	at java.util.TimerThread.run(Timer.java:505) ~[na:1.8.0_311]
大佬这是啥问题啊,我连5.7版本的数据库是正常的.好像到8版本就不行了
